backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: '{{slug}}.html'
      - label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Twitter Image
            name: twitter:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
  - label: Theme Settings
    name: settings
    identifier_field: title
    extension: json
    create: false
    delete: false
    slug: '{{slug}}'
    editor:
      preview: false
    files:
      - label: General
        name: site
        file: cms/_data/settings/site.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: General
          - hint: Full domain url (needed for a correct sitemap file)
            name: domain
            label: Domain
            widget: string
            required: false
          - name: favicon
            label: Favicon
            widget: image
            allow_multiple: false
            required: false
          - name: apple_touch_icon
            label: Apple Touch Icon
            widget: image
            allow_multiple: false
            required: false
          - name: header_additional_content
            label: Additional Content Header
            hint: Content here will be placed before </head> tag
            widget: text
            required: false
          - name: footer_additional_content
            label: Additional Content Footer
            hint: Content here will be placed before </body> tag
            widget: text
            required: false
          - name: images_optimization
            label: Images Optimization
            widget: object
            collapsed: false
            fields:
              - label: Image Formats
                name: formats
                widget: select
                multiple: true
                options:
                  - label: Avif
                    value: avif
                  - label: Webp
                    value: webp
              - label: Image Dimensions
                name: dimensions
                widget: select
                multiple: true
                options:
                  - label: '500'
                    value: 500
                  - label: '800'
                    value: 800
                  - label: '1080'
                    value: 1080
                  - label: '1600'
                    value: 1600
                  - label: '2000'
                    value: 2000
                  - label: '2600'
                    value: 2600
      - label: Colors
        name: colors
        file: cms/_data/colors.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Colors
      - label: Texts
        name: texts
        file: cms/_data/texts.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Texts
          - hint: 'Original text: On your Marks, key: -76cd2246'
            label: Text
            name: '-76cd2246'
            widget: string
          - hint: 'Original text: Ready, Set, , key: 1c0d715f'
            label: Text
            name: 1c0d715f
            widget: string
          - hint: 'Original text: Xike..., key: -179c599d'
            label: Text
            name: '-179c599d'
            widget: string
          - hint: >-
              Original text:  where content trumps follower count and earns you
              more than just likes. , key: -7d4e2797
            label: Text
            name: '-7d4e2797'
            widget: string
          - hint: "Original text: \"Xike - Influence meets\_innovation\", key: -5b0045c8"
            label: Text
            name: '-5b0045c8'
            widget: string
          - hint: 'Original text: Count Me in, key: 7d14461c'
            label: Text
            name: 7d14461c
            widget: string
      - label: Links
        name: links
        file: cms/_data/links.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Links
          - hint: 'Original link: https://forms.gle/AvNhHue2K8C78njA8, key: -387c613c'
            label: Link
            name: '-387c613c'
            widget: string
      - label: Images
        name: images
        file: cms/_data/images.json
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Images
          - label: Image
            name: 62ec0c4f
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 7d26e01b
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
          - label: Image
            name: 4c8b11c9
            widget: object
            fields:
              - name: url
                label: Image Url
                widget: image
                allow_multiple: false
                required: false
              - name: alt
                label: Image Alt
                widget: string
                required: false
publish_mode: editorial_workflow
